version: '3.8'

services:

  dcs-postgres:
    image: postgres:16.3
    container_name: dcs-postgres-supermarket
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: supermarket_service
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  dcs-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: dcs-pgadmin-supermarket
    depends_on:
      - dcs-postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 80:80
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin

networks:
  default: {}